window.videoList = [
    { src: 'https://pooveyfarmsracingtv.com/2023_Mix_Tape_Chapter_01.mp4', title: '1. Beans On Toast - Things' },
    { src: 'https://pooveyfarmsracingtv.com/2023_Mix_Tape_Chapter_02.mp4', title: '2. Ruarri Joseph - Hope for Grey Trousers' },
    { src: 'https://pooveyfarmsracingtv.com/2023_Mix_Tape_Chapter_03.mp4', title: '3. The Charlatans - The Blind Stagger' },
    { src: 'https://pooveyfarmsracingtv.com/2023_Mix_Tape_Chapter_04.mp4', title: '4. Gang of Youths - Magnolia' },
    { src: 'https://pooveyfarmsracingtv.com/2023_Mix_Tape_Chapter_05.mp4', title: '5. Catfish and the Bottlemen - 7' },
    { src: 'https://pooveyfarmsracingtv.com/2023_Mix_Tape_Chapter_06.mp4', title: '6. The Voidz - Alien Crime Lord' },
    { src: 'https://pooveyfarmsracingtv.com/2023_Mix_Tape_Chapter_07.mp4', title: '7. John Lord Fonda - So Far Away' },
    { src: 'https://pooveyfarmsracingtv.com/2023_Mix_Tape_Chapter_08.mp4', title: '8. Sir Sly - High' },
    { src: 'https://pooveyfarmsracingtv.com/2023_Mix_Tape_Chapter_09.mp4', title: '9. KONGOS - Autocorrect' },
    { src: 'https://pooveyfarmsracingtv.com/2023_Mix_Tape_Chapter_10.mp4', title: '10. renforshort - feel good inc.' },
    { src: 'https://pooveyfarmsracingtv.com/2023_Mix_Tape_Chapter_11.mp4', title: '11. hard life - BEESWAX' },
    { src: 'https://pooveyfarmsracingtv.com/2023_Mix_Tape_Chapter_12.mp4', title: '12. The Streets - Lets Push Things Forward' },
    { src: 'https://pooveyfarmsracingtv.com/2023_Mix_Tape_Chapter_13.mp4', title: '13. Flobots - Defend Atlantis' },
    { src: 'https://pooveyfarmsracingtv.com/2023_Mix_Tape_Chapter_14.mp4', title: '14. Silversun Pickups - Growing Old Is Getting Old' },
    { src: 'https://pooveyfarmsracingtv.com/2023_Mix_Tape_Chapter_15.mp4', title: '15. The Stills - Yesterday Never Tomorrows' },
    { src: 'https://pooveyfarmsracingtv.com/2023_Mix_Tape_Chapter_16.mp4', title: '16. Palomar - Our Haunt' },
    { src: 'https://pooveyfarmsracingtv.com/2023_Mix_Tape_Chapter_17.mp4', title: '17. Sunny Day Real Estate - Television' },
    { src: 'https://pooveyfarmsracingtv.com/2023_Mix_Tape_Chapter_18.mp4', title: '18. The Avalanches - Oh The Sunn!' },
    { src: 'https://pooveyfarmsracingtv.com/2023_Mix_Tape_Chapter_19.mp4', title: '19. The Constellations - We are Here to Save The Day' },
    { src: 'https://pooveyfarmsracingtv.com/2023_Mix_Tape_Chapter_20.mp4', title: '20. Grandaddy - Now Its On' },
    { src: 'https://pooveyfarmsracingtv.com/2023_Mix_Tape_Chapter_21.mp4', title: '21. The Spinto Band - Japan Is an Island' },
    { src: 'https://pooveyfarmsracingtv.com/2023_Mix_Tape_Chapter_22.mp4', title: '22. Enon - Disposable Parts' },
    { src: 'https://pooveyfarmsracingtv.com/2023_Mix_Tape_Chapter_23.mp4', title: '23. Buzzcocks - Ever Fallen in Love' },
    { src: 'https://pooveyfarmsracingtv.com/2023_Mix_Tape_Chapter_24.mp4', title: '24. TV On The Radio - Dirtywhirl' },
    { src: 'https://pooveyfarmsracingtv.com/2023_Mix_Tape_Chapter_25.mp4', title: '25. Twenty One Pilots - Heathens' },
    // ... more videos
];